name: PyPI passwordrd project-verified

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  publicar:
    name: Publicar pacote no PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip build

      - name: Build do pacote
        run: python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
